### ISSUE TITLE
Обернуть код скрипта(из ридми) в анонимную функцию

### ISSUE THREAD

**Issue by perezagruzka37** [WhiteApfel/pfelreader#1]
1. Оберните код скрипта(из ридми) в анонимную функцию, чтобы не засирать глобальное пространство имен.
2. В Виа есть косяк, юзер скрипты грузятся 2 раза. Добавьте проверку, был ли скрипт загружен ранее.
А можно кнопку рисовать в самом первом скрипте, а второй (большой) загружать при необходимости.
3. Это по сути ЮзерСкрипт. Можно расширить область применения не только на ВИА.

**Comment by WhiteApfel** [comment]
- [x] 1. Готово. Теперь функции анонимны на всех этапах.
- [x] 2. Теперь скрипт вызывает функцию, проверяющую наличие кнопки по id, в случае отсутствия создает её. "Большой" скрипт загружается после клика. 

- [ ] 3. На данный момент вижу только возможность вызова через адресную строку. Возможно, сделать дополнения для chrome или других браузеров.
