### ISSUE TITLE
Buautify script

### ISSUE THREAD

**Issue by perezagruzka37** [WhiteApfel/pfelreader#3]
;/**0. Use this! ViaBrowser concats all user scripts!  **/

**javascript:/\*📖 reader\*/**
/*\*1. Can use as bookmarklet*\*/
(function(){
if(document.getElementById('ReaderModeButton8921'))
	return;
var rb = document.createElement("div"); 
rb.id='ReaderModeButton8921';
/*\*2. Set border-radius*\*/
rb.setAttribute('style','position:absolute;top:2em;right:1em;'
**+'border-radius:10px;'**
+'padding:0.5em 0.75em;background-color:#000;opacity:0.7;z-index:999999;color:#F60');**
/*\*3. Set icon*\*/
**rb.innerHTML = "📖";**
rb.onclick=function(){
	var sc = document.createElement('script');
	sc.src='https://reader.pfel.ru/reader.js';
	document.body.appendChild(sc);
	/*\*4. View progress while loading. Supported only in Via*\*/
	**via.toast('⌛loading...');**
};
document.body.appendChild(rb); 
})()
;/**Important!**/
/**Try it!**/

**Comment by WhiteApfel** [comment]
Thank! I made some changes. But I don't want use specific commands (only for Via). The code for the button is recommended to download from server. Anyway, it is cached.

**Comment by perezagruzka37** [comment]
Type in search or url string 
javascript:alert(Object.keys(via));

Also. 
1. Don't use "  " in bookmarklet. Only '  '
2. Add ; to begin and end of script.

**Comment by WhiteApfel** [comment]
Ok
